<?= $this->renderFile('print_templates/_template_arr', array(
    'arr' => array(
        'id' => l('ID заказа на ремонт'),
        'sum' => l('Сумма за ремонт'),
        'qty_all' => l('Количество наименований'),
        'products_and_services' => l('Товары и услуги'),
        'discount' => l('Скидка на заказ'),
        'sum_with_discount' => l('Сумма заказа с учетом скидки'),
        'sum_paid' => l('Оплачено'),
        'sum_paid_in_words' => l('Оплачено прописью'),
        'product' => l('Устройство'),
        'serial' => l('Серийный номер'),
        'company' => l('Название компании'),
        'address' => l('Адрес'),
        'wh_phone' => l('Телефон склада'),
        'now' => l('Текущая дата'),
        'currency' => l('Валюта'),
        'sum_in_words' => l('Сумма за ремонт прописью'),
        'order' => l('Номер заказа'),
        'order_data' => l('Дата создания заказа'),
        'client_reg_data_1' => l('Клиент (Регистрационные данные 1)'),
        'client_reg_data_2' => l('Клиент (Регистрационные данные 2)'),
        'client_legal_address' => l('Клиент (Юридический адрес)'),
        'client_residential_address' => l('Клиент (Фактический адрес)'),
        'client_note' => l('Клиент (примечания)'),
    )
));